apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - name: jenkins-demo
        image: jenkins-demo-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-service
spec:
  type: NodePort
  selector:
    app: jenkins-demo
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001